name: PROS Project Compile Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install ARM Toolchain
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '10-2020-q4'
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Install CLI
        uses: BSFishy/pip-action@v1
        with:
          packages: pros-cli
          
      - name: Testing PROS Install 
        run: prosv5 --version
        
      - name: Build
        run: make quick
